### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by kalepail** [dplesca/stellar-vanity#1]
Using `--writetofile` flag but getting error 
`write result.txt: bad file descriptor`

**Comment by dplesca** [comment]
Hi. Can you please give me more info? What OS are you using? Do you have permissions to write in that folder?

**Comment by kalepail** [comment]
![screen shot 2018-08-27 at 4 56 11 pm](https://user-images.githubusercontent.com/4383610/44685711-1d2a8e80-aa1a-11e8-9183-40e88a7d10c2.png)

```
$ go version
go version go1.11 darwin/amd64
```

Yes to the permissions.

**Comment by dplesca** [comment]
Hi, I've finally managed to get on a mac and find the bug. It should be fixed now in version 0.2. You can compile the new version after a pull, or [download the new release](https://github.com/dplesca/stellar-vanity/releases).

**Comment by kalepail** [comment]
Works perfectly. Thanks!
